CREATE TABLE POST_ENTITY(
    ID IDENTITY PRIMARY KEY,
    TITLE VARCHAR
);

CREATE TABLE POST_LEVEL_SCORE(
    POST_ENTITY BIGINT NOT NULL,
    JUNIOR_SCORE INTEGER,
    MID_SCORE INTEGER,
    SENIOR_SCORE INTEGER
);
